### ISSUE TITLE
predetermined colors don´t show up

### ISSUE THREAD

**Issue by fkyros** [karan/atom-terminal#113]
customised properties for cmd don´t apply when triggered the cmd with this extension

**Comment by rcpeene** [comment]
I have the same problem. For some reason the colors do work on my PC upon which I installed this package many months ago, but on my new laptop, the colors show up as an odd greyish scheme.

**Comment by rcpeene** [comment]
Nevermind, the issue is fixed. Change the prompt window settings in the "default" tab, not the "properties" tab.
Altering settings in the "properties" tab, seems to affect the cmd prompt window only when run from start menu.
Running cmd.exe from System32 (and from atom) seems to only use the settings under the "defaults" tab in command prompt.
