### ISSUE TITLE
Stopped working around Atom 0.180.0

### ISSUE THREAD

**Issue by jakesankey** [karan/atom-terminal#27]

**Comment by tkw1536** [comment]
I suspect it has to do with #26, so please fix #25 @karan 

Are there any error messages showing up in the console?

**Comment by merqlove** [comment]
No, no logs, but same problem

**Comment by tkw1536** [comment]
Weird, can you check the installed version of atom-terminal?

I am using the current master on atom 1.8.1 and it works.

**Comment by merqlove** [comment]
@tkw1536 , i'm use 0.6.0 on atom 1.8.2. 
Still fail without logs.

**Comment by tkw1536** [comment]
@merqlove  I am guessing has been removed from the API. Can you try installing directly from this repository and see if that works?

If that is the case we really need to publish a new version (#25).

**Comment by merqlove** [comment]
@tkw1536, how i can do this? `git clone` into `~/.atom/packages` ?

**Comment by merqlove** [comment]
@tkw1536, yes, `master` branch works well.

**Comment by tkw1536** [comment]
Thats good news, so all we have to do is actually publish a new version. Only @karan can do this.

**Comment by karan** [comment]
Sorry for the delay forks. `0.7.0` is now published with the deprecated call removed! Thanks for the patience.

**Comment by Leeds-eBooks** [comment]
@karan Thanks for fixing this. However, since this update my terminal app is getting opened twice, i.e. two instances of the app are initialized on keypress. This is what the keybinding resolver shows, but I doubt it's the cause of the issue:

![terminal](https://cloud.githubusercontent.com/assets/4380655/6357290/3903dd24-bc5b-11e4-8859-66b3f84ce679.png)

Are there any logs I can post to help find the root cause?

**Comment by tkw1536** [comment]
@Leeds-eBooks You can try restarting atom. I had the same issue when I installed an update once.

**Comment by Leeds-eBooks** [comment]
@tkw1536 Yes, you're right. False alarm, sorry!
