### ISSUE TITLE
NODE_PATH is set to a directory inside Atom

### ISSUE THREAD

**Issue by johncmckim** [karan/atom-terminal#74]
When using the shortcut to open a powershell window on Windows, the NODE_PATH environment variable gets changed to a path inside Atom.

<img width="1216" alt="node_path issue" src="https://cloud.githubusercontent.com/assets/1297227/10899321/5a5baa80-821f-11e5-961f-88cfa679e14f.PNG">

This messes with tools like yeoman. The NODE_PATH environment variable should not be the same as if I was to open a terminal outside ATOM.

**Comment by patsissons** [comment]
The current work around for powershell is to add some args to your atom-terminal settings:
`-NoExit -Command "& { Remove-Item Env:NODE_ENV; Remove-Item Env:NODE_PATH; }"`
This will tell powershell to run the command that removes the offending node environment variables and remains open after completing.

There ought to be similar command args for Mac/Linux/Batch scripts.

This also relates to #13 and #53

**Comment by johncmckim** [comment]
That's frustrating. I don't want to end up with an ever expanding list of environment variables to remove. Would passing an empty environment object to [exec](https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback) help?

It could be worth documenting this as it is not an obvious issue that goes against in expectations. If I want to use this and get started with gulp / grunt / bower ect I don't expect to have to set a setting to get it working.

**Comment by patsissons** [comment]
I don't think any vars other than the `NODE_*` vars will need to be removed. They are in place because atom uses them specifically (i.e. `NODE_PATH` is required by `apm`) and launching a shell from the atom process brings them along for the ride. It's annoying for sure, but not really a good way around it. It would be nice if there were a way to spawn a powershell in an isolated environment.

**Comment by johncmckim** [comment]
Yea fair enough. I certainly agree with the statement about powershell.

`Start-Process` has a `-UseNewEnvironment` [argument](https://technet.microsoft.com/en-us/library/hh849848.aspx?f=255&MSPPError=-2147217396). However, I can't seem to get that to work.

If I add `-Command "& { Start-Process powershell.exe -UseNewEnvironment }"` to args the new powershell window closes without any info (removing `-UseNewEnvironment` works fine).

The [Start command](https://technet.microsoft.com/en-us/library/cc770297.aspx) also has the /i argument that starts cmd with the environment cmd was originally launched with. However, I don't think that helps in this case as the environment isn't modified before start is run.

**Comment by jscissr** [comment]
My workaround for cmd on Windows: put `/K "set NODE_PATH=& set NODE_ENV=& set GOOGLE_API_KEY="` into the Args setting.

This should work by default in my opinion. Otherwise, everyone using this module for node development will wonder why things don't work; and maybe they realise it's because they're using atom-terminal, and that their environment variables are corrupted. Then they will find this issue and set the necessary configuration.
